# Generated by Django 3.0.1 on 2019-12-31 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='content',
        ),
    ]
