# Generated by Django 3.0.1 on 2020-01-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0002_auto_20191231_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
