# Generated by Django 3.0.2 on 2020-01-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0003_auto_20200103_0537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoList',
            new_name='TodoListModel',
        ),
    ]
