# Generated by Django 2.2.9 on 2020-01-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0004_auto_20200103_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistmodel',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todolistmodel',
            name='title',
            field=models.CharField(max_length=8),
        ),
    ]
